import bcrypt from 'bcryptjs'
const product = {
  products: [
    {
      numberk: '1',
      name: 'Nike Slimgggg shittttt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      numberk: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 3.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      numberk: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      numberk: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
  users:[
    {
      name: 'Eason',
      email: 'admin@exp.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'son',
      email: 'user@exp.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    }
  ],
}
export default product
